### ISSUE TITLE
built in support for polymorphic types

### ISSUE THREAD

**Issue by Tal500** [eyalz800/zpp_bits#148]
Thanks for writing this powerful library.
There is a big elephant in the room that is missing, a support for polymorphic types, i.e. fields that their types could be implemented by any derived class.

The current solution for this is by using variant as far as I can tell, but this limits the use case for only full knowledge in compilation time(and on the same place in code). While this is great for embedded system developers and RPC, this is very limiting for the "pluggable" use case.

I believe I can implement some tricks on the user side to handle polymorphic type, like managing the subclass type registering by myself, and use std::span<const std::byte> to serialize the results bitwise(while the inner serialization implementation calls this library serialization again). The question is do this library wants to be more general and support this somehow (with no additional overhead for non-users) for easier use?

**Comment by eyalz800** [comment]
The auto registration of polymorphic types was too implicit in my opinion and also required to have a global data structure to handle all of that with a mutex (imagine loading DLL/SO at runtime and etc), plus you need to check using runtime type information that the right type was constructed to avoid security issues. Maintaining a variant is so simple, it’s also local rather than global of all types in the project, I really recommend that you simply break down your protocol to smaller and smaller variants and during each stage your variant of potential messages will be small and maintainable. I realize this adds overhead in explicitly naming the type in another location but it’s very declarative and self documented as opposed for being tasked to seatch entire project for protocol messages and try building a picture of which message can be received by each stage.

Hope I convinced you, and if not, I’m sure you can do manual registration like I’ve done in the past library as something that is very small that uses zpp::bits

**Comment by Tal500** [comment]
> The auto registration of polymorphic types was too implicit in my opinion and also required to have a global data structure that is populated at load time (pre-main) to handle all of that with a mutex (imagine loading DLL/SO at runtime and etc), plus you need to check using runtime type information that the right type was constructed to avoid security issues. Maintaining a variant is so simple, it’s also local rather than global of all types in the project, I really recommend that you simply break down your protocol to smaller and smaller variants and during each stage your variant of potential messages will be small and maintainable. I realize this adds overhead in explicitly naming the type in another location but it’s very declarative and self documented as opposed for being tasked to seatch entire project for protocol messages and try building a picture of which message can be received by each stage.
> 
> Hope I convinced you, and if not, I’m sure you can do manual registration like I’ve done in the past library as something that is very small that uses zpp::bits

Your ideas are fine on small scale, but my use case is for a big scale, that I wouldn't mind to wait a little bit extra time to parse it if that's what it takes.
I do understand though the rational to leave it to the user land, I guess it's reasonable.
