### ISSUE TITLE
problem implementing external serialisation for std::chrono::timepoint

### ISSUE THREAD

**Issue by stayprivate** [eyalz800/zpp_bits#160]
Trying to implement serialization  functions to handle std::chrono::timepoint, but to no avail.  I've already handled a bunch of custom objects, like boost::circular_buffer, llvm::SmallString, so I though I got the hang of it, seems not.   

Here is the code.

https://godbolt.org/z/eWTGhq3zz

Any suggestion much appreciated.

**Comment by eyalz800** [comment]
The external serialize(..) function needs to be either in the class namespace, or in the namespace zpp::bits, here because the std::chrono::time_point is inside std, I recommend to put the serialize(..) function in the zpp::bits namespace because it would be illegal to add it to the std namespace (by the language rules). But, you also need to add a custom serialize function for std::chrono::duration in the same way to make it work because you have defined only for time_point.

**Comment by stayprivate** [comment]
That was it , thank you.  Great piece of software, congratulation.
