### ISSUE TITLE
abstract class

### ISSUE THREAD

**Issue by stayprivate** [eyalz800/zpp_bits#161]
Hi,

class Predict 
{
...
   std::vector<std::unique_ptr<PostProcessingParams>>	m_postProcessingParams;
...
}

Where PostProcessingParams is an abstract class inherited by a bunch of other classes. m_postProcessParams are pointer to base class, and we are using polymorphism. What strategy do you recommend for handling that scenario.

Thanks.

**Comment by eyalz800** [comment]
I recommend to go for std::variant<all,your,types> then use std::visit and work with them rather than using virtual. If you really want to use virtual then you need to implement a save(..) load(..) virtual functions - the load function does the regular deserialization of a unique ptr of derived and the save just saves.

**Comment by stayprivate** [comment]
Thanks.
